### ISSUE TITLE
Is it possible to delete the arrows created?

### ISSUE THREAD

**Issue by ganesshkumar** [AlexeyBoiko/DgrmJS#1]
I tried to delete an arrow between two shapes but not able to figure out how to delete it.

**Comment by AlexeyBoiko** [comment]
Select arrow -> shape settings -> del icon
<img src="https://raw.githubusercontent.com/AlexeyBoiko/DgrmJS/doc/img/dgrmjs-del-connecting-line.gif">

**Comment by ganesshkumar** [comment]
It works. Thanks!
