### ISSUE TITLE
creating connected node when dragging the connection link

### ISSUE THREAD

**Issue by asith-w** [AlexeyBoiko/DgrmJS#23]
This is cool tool. is it possible to extend?
I need to create new connected node when Link is dragged or if user press tab key, new node is added to canvas with link.
could you give idea to extend the above feature if it is possible
![image](https://user-images.githubusercontent.com/5784846/206131083-b54e7217-5311-4035-945e-20528117a15e.png)

**Comment by AlexeyBoiko** [comment]
Hello @asith-w.

I recommend to wait for the new version. I can't promise this feature will be added, but you will get new code. I'll try to help when I finish refactoring.

Currently I'am working on completely new version. New version will have less code, code will be easier and more productive.
You can follow the progress in "dev" branch.

**Comment by asith-w** [comment]
@AlexeyBoiko Great.
I wish to contribute if I understand the code :)
