### ISSUE TITLE
Shape of links

### ISSUE THREAD

**Issue by d01010101** [AlexeyBoiko/DgrmJS#25]
Links sometimes "wiggle" so that it is not evident what they convey. I attach an example.

![diagram](https://user-images.githubusercontent.com/26835047/207894376-38933e1a-9f05-4b25-8707-b3ef55c52b9c.png)

**Comment by AlexeyBoiko** [comment]
Hello @d01010101
Thanks for reaching out.

I saw fuzzy behavior of links on mobile. I am working on new version. I believe in new version will fix this.
You can track process in "dev" branch.

**Comment by AlexeyBoiko** [comment]
New version is ready. Links is more stable.
https://dgrm.net/
