### ISSUE TITLE
[Feature request] : Text (Bold, Italic, Underline) 

### ISSUE THREAD

**Issue by yogananda-muthaiah** [AlexeyBoiko/DgrmJS#29]
Hi Alex,

yet another feature request : for Text - Bold, Italic, Underline to be made available for beautifying

**Comment by AlexeyBoiko** [comment]
Hi @yogananda-muthaiah,

Thanks for suggestion. I added headers and bold text.
I'll update dgrm.net soon. You can track updates with twitter https://twitter.com/boyko_tech

> Italic, Underline
I want to keep dgrm as simple as possible. With a minimum number of buttons. Not sure Italic, Underline is necessary. Can you provide a real diagram with Italic, Underline?

**Comment by AlexeyBoiko** [comment]
Header and bold added
https://alexey-boyko.medium.com/diagram-editor-dgrm-net-announcement-header-bold-forward-backward-5c5627a46b15
