### ISSUE TITLE
When node is dragged directly over the connected one, it jumps to another position

### ISSUE THREAD

**Issue by aleksandrbazhin** [AlexeyBoiko/DgrmJS#3]
How to reproduce:
1. Create 2 nodes
2. Connect one to another (maybe optional)
3. Drag one over another so that outgoing and incoming edge connectors are directly over each other
- the node being dragged jumps 1000 pixels or so.
Tested: latest Firefox
Possible cause: division by zero.

I am not going to use the project, just wanted to report the issue randomly.

**Comment by AlexeyBoiko** [comment]
Thank you for your help, I'll check it asap.
