### ISSUE TITLE
Nice work! how to plug DgrmJs into one application and use?

### ISSUE THREAD

**Issue by lijunhaoabroad** [AlexeyBoiko/DgrmJS#5]
I just want to know if it is possible to compile everything into one javascript file so that it can be used directly with just a script tag without putting the whole folder inside a project?

Thank you again for writing this library!

**Comment by AlexeyBoiko** [comment]
Thank you, I have to make npm. Please give me some days.

**Comment by AlexeyBoiko** [comment]
I created npm:
[![npm version](https://badge.fury.io/js/dgrm.svg)](https://badge.fury.io/js/dgrm)

and a minimalistic example:
https://github.com/AlexeyBoiko/DgrmJS-Example
